language: node_js
node_js:
- '12'
services:
- docker
before_install:
  - docker pull selenium/standalone-chrome:3.141.59-20200525
cache:
  directories:
    - node_modules
install:
   - npm install
script:
  - docker login -u $SECRET_CLOUD_LOGIN -p $SECRET_CLOUD_PASS
  - docker pull no4good597/app
  - docker run -d -p $PORT:$PORT --net="host" no4good597/app
  - npm run test
  - docker run -d -p 4444:4444 --net="host" selenium/standalone-chrome:3.141.59-20200525
  - npm run test:e2e
